manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: olsen-cole
      url-base: https://github.com/olsen-cole
  projects:
    - name: zmk
      remote: zmkfirmware
      # Pinning to V0.2, instead of main for compatibility
      revision: v0.2
      # revision: main
      import: app/west.yml
    - name: zmk-smart-toggle
      remote: caksoylar
      revision: main
    - name: zmk-rgbled-widget
      remote: olsen-cole
      revision: main
  self:
    path: config